service: sls-course

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
  
resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}

functions:
  users:
    handler: src/handlers/users.handler
    events:
      - http:
          method: POST
          path: /users

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn