service: sls-course

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
  
resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}

functions:
  usersPost:
    handler: src/handlers/users.handler
    events:
      - http:
          method: POST
          path: /users

  usersGet:
    handler: src/handlers/usersGet.handler
    events:
      - http:
          method: GET
          path: /users

  userGet:
    handler: src/handlers/userGet.handler
    events:
      - http:
          method: GET
          path: /user/{id}

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
  dynamodb:
    stages:
      - dev
    start:
      host: dynamodb.local
      port: 8000
      inMemory: true
      migrate: true
      shareDb: true
    migration:
      dir: offline/migrations