version: '3'
services:
  serverless.app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
    volumes:
      - ..:/sls-course:cached
    command: sleep infinity
  dynamodb.local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./db:/home/dynamodblocal/db
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/db"]
  dynamodb.admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment: 
      - DYNAMO_ENDPOINT=http://dynamodb.local:8000 dynamodb-admin